MODBUSGW_VERSION = v0.9.3
MODBUSGW_SITE = https://github.com/camradeling/modbusgw.git
MODBUSGW_SITE_METHOD = git
MODBUSGW_GIT_SUBMODULES = YES
MODBUSGW_LICENSE = GPL-2.0
MODBUSGW_LICENSE_FILES = LICENSE

$(eval $(cmake-package))