#!/bin/bash
IFACE=ppp0
TTL=64
#route add default gw $5
#route add -host 109.167.231.7 dev ppp0 ### ???? it's need?

### set ttl value == 64, for work different sim-card
if [[ `iptables -L -v -n -t mangle | grep ${IFACE} | grep TTL | awk '{print $3}'` == "TTL" ]]; then
	iptables -t mangle -D POSTROUTING -o ${IFACE} -j TTL --ttl-set ${TTL}
fi
iptables -t mangle -I POSTROUTING -o ${IFACE} -j TTL --ttl-set ${TTL}
